apiVersion: v1
kind: Service
metadata:
  name: {{ include "p3m.fullname" . }}-frontend-svc
  labels:
    {{- include "p3m.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "p3m.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
