{{- if .Values.config.auth.google.enabled -}}
{{- $host := first .Values.ingress.hosts }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "p3m.fullname" . }}-auth-google
stringData:
  GOOGLE_CLIENT_ID: {{ (required "É obrigatório fornecer um CLIENT_ID do Google para ativar a autenticação" .Values.config.auth.google.client_id) | quote }}
  GOOGLE_CLIENT_SECRET: {{ (required "É obrigatório fornecer um CLIENT_SECRET do Google para ativar a autenticação" .Values.config.auth.google.secret) | quote }}
  GOOGLE_REDIRECT_URI: "https://{{ $host.host }}/api/auth/google/callback/"
type: Opaque
{{- end -}}
