{{- if .Values.config.auth.govbr.enabled -}}
{{- $host := first .Values.ingress.hosts }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "p3m.fullname" . }}-auth-govbr
stringData:
  GOVBR_CLIENT_ID: {{ (required "É obrigatório fornecer um CLIENT_ID do Gov.BR para ativar a autenticação" .Values.config.auth.govbr.client_id) | quote }}
  GOVBR_CLIENT_SECRET: {{ (required "É obrigatório fornecer um CLIENT_SECRET do Gov.BR para ativar a autenticação" .Values.config.auth.govbr.secret) | quote }}
  GOVBR_REDIRECT_URI: "https://{{ $host.host }}/api/auth/govbr/callback/"
type: Opaque
{{- end -}}
