apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "p3m.fullname" . }}-statics
  labels:
    {{- include "p3m.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
{{- with .Values.pvc }}
  {{- if .keep }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  volumeMode: Filesystem
  {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- end }}
  accessModes:
    {{- range .storage.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .storage.className }}
  storageClassName: {{ .storage.className | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .storage.size }}
{{- end }}
