kind: Secret
apiVersion: v1
metadata:
  name: {{ include "p3m.fullname" . }}-secret
stringData:
  {{-  with .Values.backend.config }}
  p3m-database-url: {{ .databaseURL | quote }}   
  p3m-secret-key: {{ .secretKey | quote }}
  {{- end }} 
type: Opaque
